name: Static Build

on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'PaulLopez12/LearningPython'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Run build script
        run: |
          chmod +x ./Frontend/link_bio/remote_build.sh
          ./Frontend/link_bio/remote_build.sh

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update static build
          commit_user_name: PaulLopez12
          commit_user_email: 67396684+PaulLopez12@users.noreply.github.com
          commit_author: PaulLopez12 <67396684+PaulLopez12@users.noreply.github.com>
